SELECT * FROM customers
WHERE CUSTOMER_ID IN
  (SELECT customer_id FROM ORDERS
  GROUP BY customer_id
  HAVING
   SUM(CASE WHEN PRODUCT_NAME='A'THEN 1 ELSE 0 END) >=1 
   AND SUM(CASE WHEN PRODUCT_NAME='B'THEN 1 ELSE 0 END)>=1 
   AND SUM(CASE WHEN PRODUCT_NAME='C'THEN 1 ELSE 0 END)=0
  ) order by customer_name;
